services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend/src:/frontend/src"
    image: econnect-frontend:latest
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/backend"
    image: econnect-backend:latest
    ports:
      - "3030:3030"

