version: '3.8'

services:
  frontend:
    build:
      context: ./eConnect-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./eConnect-backend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"

