name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - build/*
  pull_request:
    branches:
      - main
      - build/*

jobs:
  setup:
    name: Checkout Repositories and Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout eConnect Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          clean: false

      - name: Checkout eConnect-frontend Repository
        uses: actions/checkout@v4
        with:
          repository: zivevo/eConnect-frontend
          path: frontend
          token: ${{ secrets.ACCESS_TOKEN }}

      - name : Debug
        run: ls -la

      - name: Checkout eConnect-backend Repository
        uses: actions/checkout@v4
        with:
          repository: zivevo/eConnect-backend
          path: backend
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: setup_artifact
          path: ./
        
      - name : Temp 
        run : ls -la

  docker-compose:
    name: Docker Compose Setup
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: setup_artifact
          path: ./

      - name : Debug
        run: pwd
        
      - name : Debug
        run: ls -la

      - name: Pull Docker Images
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Pull Docker Images
        run: docker pull oven/bun && docker pull node

      - name: Start Docker Compose
        run: docker-compose up --build -d

      - name: Wait for Services to be Ready
        run: sleep 10 

  # tests:
  #   name: Run Tests and Lint Checks
  #   runs-on: ubuntu-latest
  #   needs: docker-compose

  #   steps:
  #     - name: Backend Tests
  #       run: docker-compose exec backend npm test

  #     - name: Backend Lint
  #       run: docker-compose exec backend npm run lint

  #     - name: Frontend Lint
  #       run: docker-compose exec frontend npm run lint

  deploy:
    name: Deployment (Optional)
    runs-on: ubuntu-latest
    needs: docker-compose

    steps:
      - name: Deploy to Environment
        run: echo "Deploy step goes here"
